// You are given two strings s and t.
// String t is generated by random shuffling string s and then add one more letter at a random position.
// Return the letter that was added to t.

const findTheDiff = (s, t) => {
    // Turn s into an array using split
    let arrayS = s.split('');
    let arrayT = t.split('');

    // Iterate through t looking to see if the character exists in the array of s
    for (let i = 0; i < arrayT.length; i++) {

        // Check if on final character
        if (!arrayT[i+1]) {
            return arrayT[i];
        }
        // If it exists, pop it from the array, continue to iterate
        if (arrayS.includes(arrayT[i])) {
            let index = arrayS.indexOf(arrayT[i]);
            arrayS.splice(index, 1); // Remove the character
        } else {
            console.log('FOUND THE VALUE');
            return arrayT[i];
        }
        
    }
    // Return the letter
}


// Test Cases
console.log(findTheDiff("abcd", "abcde" )); // e
console.log(findTheDiff("", "y")); // y
console.log(findTheDiff("a", "aa")); // a
console.log(findTheDiff("ae", "aea")); // a

